# Docker Compose para Dashboard IPTV
# Para desenvolvimento local ou deploy alternativo

version: '3.8'

services:
  # Aplicação Next.js
  dashboard-iptv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard-iptv
    ports:
      - "3000:3000"
    environment:
      # Banco de Dados
      - DB_HOST=mysql-db
      - DB_USER=dashboard_user
      - DB_PASSWORD=dashboard_password_123
      - DB_NAME=dashboard_iptv
      - DB_PORT=3306
      
      # Aplicação
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_VERSION=1.0.0
      - JWT_SECRET=sua_chave_jwt_super_secreta_aqui_32chars_exemplo
      - ENCRYPTION_KEY=32characterslongencryptionkey123
      
      # Cron Jobs
      - CRON_SECRET=sua_chave_secreta_para_cron_jobs_exemplo
      - NEXT_PUBLIC_CRON_SECRET=sua_chave_secreta_para_cron_jobs_exemplo
      
      # Evolution API (opcional)
      - EVOLUTION_API_URL=
      - EVOLUTION_API_KEY=
    volumes:
      - ./uploads:/app/public/uploads
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dashboard-network

  # Banco de Dados MySQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-dashboard-iptv
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=dashboard_iptv
      - MYSQL_USER=dashboard_user
      - MYSQL_PASSWORD=dashboard_password_123
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/backup-dados-importacao.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=-03:00
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - dashboard-network

  # phpMyAdmin (opcional - para administração do banco)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-dashboard
    environment:
      - PMA_HOST=mysql-db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root_password_123
      - MYSQL_ROOT_PASSWORD=root_password_123
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
    restart: unless-stopped
    networks:
      - dashboard-network
    profiles:
      - admin # Use: docker-compose --profile admin up

volumes:
  mysql_data:
    driver: local

networks:
  dashboard-network:
    driver: bridge

# Comandos úteis:
# 
# Iniciar todos os serviços:
# docker-compose up -d
# 
# Iniciar com phpMyAdmin:
# docker-compose --profile admin up -d
# 
# Ver logs:
# docker-compose logs -f dashboard-iptv
# 
# Parar todos os serviços:
# docker-compose down
# 
# Parar e remover volumes (CUIDADO - apaga dados):
# docker-compose down -v
# 
# Rebuild da aplicação:
# docker-compose up -d --build dashboard-iptv
# 
# Backup do banco:
# docker-compose exec mysql-db mysqldump -u root -p dashboard_iptv > backup.sql
# 
# Restaurar backup:
# docker-compose exec -T mysql-db mysql -u root -p dashboard_iptv < backup.sql